[project]
name = "phenotype2phenopacket"
version = "0.6.17"
description = ""
authors = [{ name = "Yasemin Bridges", email = "y.bridges@qmul.ac.uk" }]
requires-python = ">=3.10,<4.0"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pandas>=2.0.0,<3",
    "phenopackets>=2.0.2,<3",
    "oaklib>=0.6.0,<0.7",
    "click>=8.1.3,<9",
    "pheval>=0.7.0,<0.8",
    "linkml==1.7.4",
    "setuptools<82",
]

[project.scripts]
p2p = "phenotype2phenopacket.cli:main"

[dependency-groups]
dev = [
    "pytest>=7.2.0,<8",
    "coverage>=6.5.0,<7",
    "black>=22.12.0,<23",
]

[tool.uv]
default-groups = "all"

[tool.hatch.build.targets.sdist]
include = ["src/phenotype2phenopacket"]

[tool.hatch.build.targets.wheel]
include = ["src/phenotype2phenopacket"]

[tool.hatch.build.targets.wheel.sources]
"src/phenotype2phenopacket" = "phenotype2phenopacket"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = [
    "src"
]

[tool.black]
line-length = 100
target-version = ["py39", "py310"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
include_trailing_comma = true
reverse_relative = true
